version: '3.7'
services:
  mysql:
    container_name: poc-mysql
    image: mysql:8-debian
    environment:
      - MYSQL_DATABASE=poc_db
      - MYSQL_USER=seymour
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - poc

  php:
    container_name: poc-php
    platform: linux/x86_64
    build: .docker/php
    ports: [ '9002:9000' ]
    volumes: [ '${CI_PROJECT_DIR:-.}:/var/www' ]
    networks:
      - poc

  nginx:
    container_name: poc-nginx
    build: .docker/nginx
    ports: [ '88:80' ]
    volumes: [ '${CI_PROJECT_DIR:-.}:/var/www' ]
    networks:
      - poc
networks:
  poc:
